'use client';

import { useState, useCallback, useRef } from 'react';
import { Button } from './ui/button';
import { useGraph } from '../store/useGraph';
import { useExplorer } from '../store/useExplorer';
import type { ProjectGraph } from '../types/graph';

export default function UploadPanel() {
  const { loadGraph } = useGraph();
  const { loadGraph: explorerLoadGraph } = useExplorer();
  const [isDragging, setIsDragging] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const validateGraph = (data: any): data is ProjectGraph => {
    return (
      data &&
      typeof data === 'object' &&
      Array.isArray(data.nodes) &&
      Array.isArray(data.edges) &&
      typeof data.projectName === 'string'
    );
  };

  const handleFile = useCallback(
    (file: File) => {
      if (!file.name.endsWith('.json')) {
        setError('Please upload a JSON file.');
        return;
      }

      setError(null);
      setIsLoading(true);

      const reader = new FileReader();

      reader.onload = (e) => {
        try {
          const text = e.target?.result as string;
          const parsed = JSON.parse(text);

          if (validateGraph(parsed)) {
            loadGraph(parsed);
            explorerLoadGraph(parsed);
            setError(null);
          } else {
            setError(
              'Invalid graph file. Please make sure you ran the CLI tool and are uploading the correct graph.json file.'
            );
          }
        } catch (err) {
          setError('Failed to parse JSON file. Please check the file format.');
        } finally {
          setIsLoading(false);
        }
      };

      reader.onerror = () => {
        setError('Failed to read file.');
        setIsLoading(false);
      };

      reader.readAsText(file);
    },
    [loadGraph]
  );

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setIsDragging(false);

      const files = e.dataTransfer.files;
      if (files.length > 0) {
        handleFile(files[0]);
      }
    },
    [handleFile]
  );

  const handleFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const files = e.target.files;
      if (files && files.length > 0) {
        handleFile(files[0]);
      }
    },
    [handleFile]
  );

  const handleClick = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 flex items-center justify-center p-8">
      <div className="max-w-2xl w-full space-y-8">
        {/* Header */}
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-bold text-white">Next.js Codebase Visualizer</h1>
          <p className="text-slate-400 text-lg">
            Upload the graph.json file generated by the CLI tool
          </p>
        </div>

        {/* Upload Zone */}
        <div
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
          onClick={handleClick}
          className={`
            relative border-2 border-dashed rounded-xl p-16 
            transition-all duration-200 cursor-pointer
            ${
              isDragging
                ? 'border-blue-500 bg-blue-500/10'
                : 'border-slate-600 hover:border-slate-500 bg-slate-800/50'
            }
          `}
        >
          <input
            ref={fileInputRef}
            type="file"
            accept=".json"
            onChange={handleFileChange}
            className="hidden"
          />

          <div className="flex flex-col items-center justify-center space-y-4">
            {/* Upload Icon */}
            <svg
              className={`w-16 h-16 ${isDragging ? 'text-blue-500' : 'text-slate-400'}`}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
              />
            </svg>

            {/* Text */}
            <div className="text-center">
              <p className="text-xl text-white font-medium">
                {isDragging ? 'Release to load' : 'Drop your graph.json here'}
              </p>
              <p className="text-sm text-slate-400 mt-2">or click to browse</p>
            </div>

            {/* Loading State */}
            {isLoading && (
              <div className="text-blue-400 text-sm font-medium animate-pulse">
                Parsing graph...
              </div>
            )}
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="bg-red-500/10 border border-red-500 rounded-lg p-4">
            <p className="text-red-400 text-sm">{error}</p>
          </div>
        )}

        {/* CLI Command Example */}
        <div className="space-y-3">
          <p className="text-slate-400 text-sm">
            Don&apos;t have a graph.json file? Run the CLI tool:
          </p>
          <div className="bg-slate-950 rounded-lg p-4 font-mono text-sm text-slate-300 border border-slate-700">
            <code>npx ts-node src/index.ts ./your-nextjs-project</code>
          </div>
        </div>
      </div>
    </div>
  );
}
